spring:

  datasource:

    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/metrikano_auth_db
    username: metrikano_auth_user
    password: metrikano_auth_pass

    tomcat:

      test-on-borrow: true
      validation-query: SELECT 1

  liquibase:
    change-log: classpath:/migrations/changelog-master.yml
    database-change-log-lock-table: database_change_log_locking
    database-change-log-table: database_change_log