spring:

  cloud:

    config:

      server:

        native:

          search-locations: classpath:microservices/{application}     

    consul:

      config:

        enabled: true
        prefix: config

      discovery:

        register: true
        enabled: true

    service-registry:

      auto-registration:

        enabled: true

  profiles:

    active: native

    security:

      basic:

        enabled: true

        user:

          name: config-user

          password: config-password

          roles: SYSTEM

jwt:
  
  properties:

    header: Authorization
    secret-key: fnreskjdfn4p3ithn3q[04tfraf
    expires-at: 600          