spring:

  kafka:

    consumer:

      bootstrap-servers: ["kafka-service:9092"]
      offset-type: earliest
      topics: ["clickhouse-user-topic", "clickhouse-classify-topic"]
      group-id: "clickhouse-group"

  clickhouse:
  
    host: clickhouse-service
    port: 8123
    database: metrikano_db
    user: default
    password: ""    