FROM confluentinc/cp-kafka:5.0.2
MAINTAINER Andrey Romanov <steampart@gmail.com>

ENV KAFKA_BROKER_ID ignored
ENV KAFKA_ZOOKEEPER_CONNECT ignored
ENV KAFKA_ADVERTISED_LISTENERS ignored

ADD run.sh /run.sh

CMD ["/run.sh"] 